//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Eid { get; set; }
        public string Ename { get; set; }
        public Nullable<decimal> ESal { get; set; }
        public Nullable<bool> EGen { get; set; }
        public Nullable<System.DateTime> EDOB { get; set; }
        public int Did { get; set; }
    
        public virtual Department tbl_Dpt { get; set; }
    }
}
