//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int Id { get; set; }
        public int UserUserId { get; set; }
        public int tbl_RoleRoleId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Role tbl_Role { get; set; }
    }
}
