//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAuthenticationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dpt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Dpt()
        {
            this.tbl_Emp = new HashSet<tbl_Emp>();
        }
    
        public int Did { get; set; }
        public string Dname { get; set; }
        public string HOB { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Emp> tbl_Emp { get; set; }
    }
}
